### ISSUE TITLE
Wrong values coming back.

### ISSUE THREAD

**Issue by Kyderman** [coolaj86/s2-geometry-javascript#3]
I get the completely wrong values back using this over the normal node library.

11464666304699432960 comes back from you.

5220233617774477312 comes from the traditional.

The traditional works perfectly, but this doesnt :/

**Comment by coolaj86** [comment]
What's the example? Are you using lat/lon or a key?

**Comment by coolaj86** [comment]
Give me something I can test with and I'll figure it out.

Which is "the traditional"? that you're referring to? I've been testing against "s2geometry-node"

**Comment by Kyderman** [comment]
So, in many of the pokemon apis you have something like this

    /**
	 * Utility method to get all the S2 Cell IDs in a given radius.
	 * Ported from https://github.com/tejado/pgoapi/blob/master/pokecli.py
	 */
	function getCellIDs(radius, lat, lng) {
	     var cell = new s2.S2CellId(new s2.S2LatLng(lat, lng)),
	        parentCell = cell.parent(15),
	        prevCell = parentCell.prev(),
	        nextCell = parentCell.next(),
	        cellIDs = [parentCell.id()];

	    for (var i = 0; i < radius; i++) {
	        cellIDs.unshift(prevCell.id());
	        cellIDs.push(nextCell.id());
	        prevCell = prevCell.prev();
	        nextCell = nextCell.next();
	    }
	    console.log(cellIDs);
	    return cellIDs;
	}



Im using this with this library

    /**
	 * Utility method to get all the S2 Cell IDs in a given radius.
	 * Ported from https://github.com/tejado/pgoapi/blob/master/pokecli.py
	 */
	function getNeighbors(lat, lng, step) {
	    //var step = 10;
	    var level = 15;
	    var origin = S2.latLngToQuadkey(lat, lng, level);
	    var walk = [];
	    // 10 before and 10 after
	    var next = S2.nextKey(origin);
	    var prev = S2.prevKey(origin);
	    var i;

	    for (i = 0; i < step; i++) {
	        walk.unshift(S2.toId(prev));
	        prev = S2.prevKey(prev);
	    }

	    walk.push(S2.toId(origin));

	    for (i = 0; i < step; i++) {
	        // in range(10):
	        walk.push(S2.toId(next));
	        next = S2.nextKey(next);
	    }
	    console.log(walk);
	    return walk;
	}


With the original node gallery using lat:51.352085106718384 and lng:-2.9877930879592896

I get the values beginning with 5, with this library, they begin with 1's.

As such, it isnt working :/

**Comment by coolaj86** [comment]
Thanks!

I think I know what it is... brb...

**Comment by Kyderman** [comment]
Ok buddy!

If you could fix it, that would be great, nothing seems to like that old library, apart from Windows with VS installed the eyes! hahaha

**Comment by Kyderman** [comment]
That seems to have fixed it all up.

Getting the same values back from both functions now.

**Comment by coolaj86** [comment]
This was the real fix: https://github.com/coolaj86/s2-geometry-javascript/commit/68274eb677be0338984b0c7d59290ec323c47e67

Aside from the previous padding errors, it can essentially it be boiled down to a one-line change:
```
var initialSquare = (face % 2) ? 'd' : 'a';
```
