### ISSUE TITLE
Incorrect Quadkey and CellId encoding of LatLng -43.525166,172.655096

### ISSUE THREAD

**Issue by coolaj86** [coolaj86/s2-geometry-javascript#6]
`s2geometry-node` produces `'7868221231537848320' '3/122120301030023' '-43.525166,172.655096'`

`s2-geometry` v1.2.1 produces `'8678661352471920640' '7/00320121210021'`

```
110110100110001100010011000010111000000000000000000000000000000 // 7868221231537848320
111100001110000110011001000010011000000000000000000000000000000 // 8678661352471920640
```

It's either a padding bug or an issue with the GPS conversion (an overflow or wrap perhaps). `7` isn't a valid face.

Update:
-----

`7/00320121210021` was a padding issue (in `.toKey()`) when converting from `8678661352471920640` (was missing the leading `0`.

However `8678661352471920640` actually represents `3/300320121210021` (not `3/100320121210021`), which revealed a second padding issue (in `.toId()`)

The 3rd issue is with the LatLng to Quadkey conversion...

**Comment by coolaj86** [comment]
Update
---------

I modified https://github.com/golang/geo to print out the debug values:

```
f 3
u 0.9576576934048505
v -0.12889961842252406
i 1056555009
j 441532418
lat lng: -43.525166   172.655096
uint64 7868221231537848320
quadkey 3/122120301030023
token 6d318985c
```

**Comment by beuted** [comment]
Using this fork made it work it work on windows! https://github.com/Daplie/Pokemon-GO-node-api
Thanks a lot.
Looking forward for the PR.

**Comment by coolaj86** [comment]
This was the fix: https://github.com/coolaj86/s2-geometry-javascript/commit/68274eb677be0338984b0c7d59290ec323c47e67

Essentially it can be boiled down to a one-line change:
```
var initialSquare = (face % 2) ? 'd' : 'a';
```
